version: '3.8'

services:
  spring-app:
    build: ..
    container_name: spring-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: testpassword
    networks:
      - mysql-network

networks:
  mysql-network:
    external: true